JobId: results/mhatever_output/cmd.txt:::results/mhatever_output/sentinel.txt:::results/mhatever_output/stderr.txt:::results/mhatever_output/stdout.txt
Class: MultiFileGeneratingJob
Input jobs:
	FIresults/mhatever_output/cmd.txt:::results/mhatever_output/sentinel.txt:::results/mhatever_output/stderr.txt:::results/mhatever_output/stdout.txt_build_cmd_func (FunctionInvariant)
	FIresults/mhatever_output/cmd.txt:::results/mhatever_output/sentinel.txt:::results/mhatever_output/stderr.txt:::results/mhatever_output/stdout.txt_call_afterwards (FunctionInvariant)


Exception: ValueError whatever run failed. Error was: Return code != 0: 1. Cmd was: ['bash', '-c', 'echo was 1; exit 1']
{bold('Traceback')} (most recent call last):
/home/finkernagel/upstream/imtmarburg/venv/lib/python3.9/site-packages/pypipegraph2/jobs.py":760, in run
	  757 
	  758                         try:
	> 759                             self.generating_function(*input)
	  760                             stdout.flush()
	  761                             stderr.flush()
	  762                             # else:
Locals:
	          aborted = <function MultiFileGeneratingJob.run.<locals>.aborted at 0x7ff1298710d0>
	      all_present = False
	      captured_tb = None
	      del_counter = 0
	                e = whatever run failed. Error was: Return code != 0: 1. Cmd was: ['bash', '-c', 'echo was 1; exit 1']
	  error_exit_code = 1
	    exception_out = <_io.BufferedRandom name='.ppg/run/0.exception'>
	   exception_type = <class 'ValueError'>
	  exception_value = whatever run failed. Error was: Return code != 0: 1. Cmd was: ['bash', '-c', 'echo was 1; exit 1']
	               fn = results/mhatever_output/stdout.txt
	historical_output = {}
	            input = ([PosixPath('results/mhatever_output/cmd.txt'), PosixPath('results/mhatever_output/sentinel.txt'), PosixPath('results/mhatever_output/stderr.txt'), PosixPath('results/mhatever_output/stdout.txt')],)
	           runner = <pypipegraph2.runner.Runner object at 0x7ff1297d5c40>
	             self = MultiFileGeneratingJob: results/mhatever_output/cmd.txt:::results/mhatever_output/sentinel.txt:::results/mhatever_output/stderr.txt:::results/mhatever_output/stdout.txt
	           stderr = <_io.TextIOWrapper name='.ppg/run/1660115575.85_0.stderr' mode='w+' encoding='UTF-8'>
	          stderr_ = <_io.TextIOWrapper name="<_io.FileIO name=8 mode='rb+' closefd=True>" mode='r+' encoding='utf-8'>
	           stdout = <_io.TextIOWrapper name='.ppg/run/1660115575.85_0.stdout' mode='w+' encoding='UTF-8'>
	          stdout_ = <_io.TextIOWrapper name="<_io.FileIO name=6 mode='rb+' closefd=True>" mode='r+' encoding='utf-8'>
	               tb = <traceback object at 0x7ff129880e80>
	 traceback_dumped = False

/home/finkernagel/upstream/imtmarburg/venv/lib/python3.9/site-packages/pypipegraph2/ppg1_compatibility.py":421, in wrapper
	  418 
	  419         def wrapper(of):  # pragma: no cover - runs in spawned process
	> 420             function()
	  421             if not isinstance(of, list):
	  422                 of = [of]
	  423             for a_filename in of:
Locals:
	function = <function ExternalAlgorithm.get_run_func.<locals>.do_run at 0x7ff12986a9d0>
	      of = [PosixPath('results/mhatever_output/cmd.txt'), PosixPath('results/mhatever_output/sentinel.txt'), PosixPath('results/mhatever_output/stderr.txt'), PosixPath('results/mhatever_output/stdout.txt')]

/home/finkernagel/upstream/imtmarburg/mbf/src/mbf/externals/externals.py":210, in do_run
	  207                     call_afterwards()
	  208             else:
	> 209                 raise ValueError(
	  210                     f"{self.name} run failed. Error was: {ok}. Cmd was: {cmd}"
	  211                 )
	  212 
Locals:
	       arguments = 1
	 call_afterwards = None
	             cmd = ['bash', '-c', 'echo was 1; exit 1']
	         cmd_out = results/mhatever_output/cmd.txt
	             cwd = None
	              ok = Return code != 0: 1
	       op_stderr = <_io.BufferedWriter name='results/mhatever_output/stderr.txt'>
	       op_stdout = <_io.BufferedWriter name='results/mhatever_output/stdout.txt'>
	output_directory = results/mhatever_output
	               p = <Popen: returncode: 1 args: ['bash', '-c', 'echo was 1; exit 1']>
	            self = <test_external_algorithm.WhateverAlgorithm object at 0x7ff1297e4280>
	        sentinel = results/mhatever_output/sentinel.txt
	      start_time = 1660115575.8534954
	          stderr = results/mhatever_output/stderr.txt
	          stdout = results/mhatever_output/stdout.txt

Exception (repeated from above): ValueError whatever run failed. Error was: Return code != 0: 1. Cmd was: ['bash', '-c', 'echo was 1; exit 1']

job stdout:
bash -c echo was 1; exit 1


job stderr:
